const express=require("express");
const bodyParser=require("body-parser");
const app=express();
app.use(bodyParser.urlencoded({extended:true}));
app.use(express.static("public"));
app.set("view engine","ejs");
app.use("/register",require("./routes/register"));
app.use("/admin",require("./routes/admin"));
app.use("/qr",require("./routes/qr"));
app.get("/",(req,res)=>res.sendFile(__dirname+"/public/festflow.html"));
app.listen(3000,()=>console.log("Server running http://localhost:3000"));
